services:
  saboga-frontend:
    build:
      context: ../
      dockerfile: ./frontend-testing/Dockerfile
    image: saboga-frontend:latest
    container_name: saboga-frontend
    labels:
      - "traefik.http.routers.saboga-frontend.rule=Host(`saboga.localhost`)"
      - "traefik.http.routers.saboga-frontend.tls=true"
    expose:
      - "4173"
    networks:
      - reverse-proxy
      - saboga-api

networks:
  reverse-proxy:
    name: api-testing_reverse-proxy
    external: true
  saboga-api:
    name: api-testing_saboga-api
    external: true
