services:
  saboga-frontend:
    build:
      context: ../
      dockerfile: ./dev.Dockerfile
    container_name: saboga-frontend
    develop:
      watch:
        - action: sync
          path: ../
          target: /app
    labels:
      - "traefik.http.routers.saboga-frontend.rule=Host(`saboga.localhost`)"
      - "traefik.http.routers.saboga-frontend.tls=true"
      - "traefik.http.services.saboga-frontend.loadbalancer.server.port=5173"
    expose:
      - "5173"
    networks:
      - saboga-reverse-proxy
      - saboga-api

networks:
  saboga-reverse-proxy:
    name: saboga-reverse-proxy
    external: true
  saboga-api:
    name: saboga-api
    external: true
