services:
  saboga-frontend:
    build:
      context: ../
      dockerfile: ./Dockerfile
    container_name: saboga-frontend
    labels:
      - "traefik.http.routers.saboga-frontend.rule=Host(`saboga.localhost`)"
      - "traefik.http.routers.saboga-frontend.tls=true"
    expose:
      - "4173"
    networks:
      - saboga-reverse-proxy
      - saboga-api

networks:
  saboga-reverse-proxy:
    name: saboga-reverse-proxy
    external: true
  saboga-api:
    name: api-testing_saboga-api
    external: true
