name: Make sure that the version is bumped

on:
  pull_request:

jobs:
  check_version:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ruberhauptmann/saboga-frontend:latest
      options: --user root
    if: ${{ startsWith(github.head_ref, 'release') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check version
        run: ./check_version.sh
